language: cpp
script: rake
compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev || apt-cache search libboost
  - sudo gem install cucumber
