language: cpp
script: rake
compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get -qq install g++-4.8
  - sudo apt-get install -y libboost1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev || apt-cache search libboost
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi

install: gem install cucumber rspec
