language: objective-c

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: false
      env: CMAKE_COMPILER=clang++
      addons:
        apt:
          packages:
            - libboost1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
          sources:
            - boost-latest
    - os: linux
      sudo: false
      env: CMAKE_COMPILER=g++-4.8
      addons:
        apt:
          packages:
            - g++-4.8
            - libboost1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
    - os: osx
      sudo: required
      env: CMAKE_COMPILER=clang++
      before_install:
        - brew update
        - brew install boost

install: gem install cucumber rspec

script: CXX=${CMAKE_COMPILER} rake
