language: cpp
sudo: false
script: rake

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++
      addons:
        apt:
          packages:
            - libboost1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
          sources:
            - boost-latest
    - os: linux
      env: CC=gcc-4.8 CXX=gcc++-4.8
      addons:
        apt:
          packages:
            - g++-4.8
            - libboost1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest

install: gem install cucumber rspec
